steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/gravityzone-mock/gravityzone-mock:latest'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/gravityzone-mock/gravityzone-mock:latest'

substitutions:
  _REGION: europe-west1
