# TODO: update runtime if needed
runtime: python311
entrypoint: gunicorn -b :$PORT -w 4 --timeout 120 app:app

env_variables:
  # TODO: replace with your auth scheme variables
  AUTH_API_KEY: "change-me"
  # AUTH_USERNAME: "test-user"
  # AUTH_PASSWORD: "test-secret"
  DEBUG: "False"
