runtime: python311
entrypoint: gunicorn -b :$PORT -w 4 --timeout 120 app:app

env_variables:
  COMPANY_ID: "gz-company-001"
  COMPANY_NAME: "Business Corp"
  NUM_ENDPOINTS: "8"
  NUM_INCIDENTS: "25"
  DEBUG: "False"
