"""
REST file endpoints for GravityZone investigation package upload/download.

These do NOT use JSON-RPC — they are plain HTTP multipart/binary endpoints.
"""
import io
import zipfile
from flask import Blueprint, request, jsonify, Response
from auth import require_basic_auth

storage_bp = Blueprint('storage', __name__)


def _make_investigation_zip():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('investigation_report.txt', (
            'GravityZone Investigation Package\n'
            'Generated by XSIAM Mock Server\n'
            'Endpoint: DESKTOP-001\n'
            'Report Date: 2026-06-09\n'
            'Status: Complete\n'
        ))
        zf.writestr('processes.csv', (
            'pid,name,path,hash,parent_pid,user\n'
            '1234,cmd.exe,C:\\Windows\\System32\\cmd.exe,'
            'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3,1000,SYSTEM\n'
            '5678,powershell.exe,C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe,'
            'b3a8c3e9f4d5e6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1,1234,BUSINESSCORP\\user\n'
        ))
        zf.writestr('network_connections.csv', (
            'src_ip,dst_ip,dst_port,proto,state,process\n'
            '192.168.1.10,185.220.101.47,443,TCP,ESTABLISHED,powershell.exe\n'
            '192.168.1.10,8.8.8.8,53,UDP,CLOSED,svchost.exe\n'
        ))
        zf.writestr('events.csv', (
            'timestamp,event_type,details\n'
            '2026-06-09T11:55:00Z,FileCreate,C:\\Windows\\Temp\\mal.exe\n'
            '2026-06-09T11:55:01Z,ProcessCreate,powershell.exe -enc ...\n'
            '2026-06-09T11:55:05Z,NetworkConnect,185.220.101.47:443\n'
        ))
    buf.seek(0)
    return buf.read()


@storage_bp.route('/storage/<bucket>', methods=['POST'])
@require_basic_auth
def upload_file(bucket):
    if 'file' not in request.files:
        return jsonify({'error': 'No file part in request'}), 400

    import uuid, random, string
    file_id = uuid.uuid4().hex
    task_id = uuid.uuid4().hex

    return jsonify({
        'status': 'success',
        'additionalData': {
            'taskId': task_id,
            'bucket': bucket,
            'fileId': file_id,
        },
    }), 200


@storage_bp.route('/storage/<bucket>/<filename>', methods=['GET'])
@require_basic_auth
def download_file(bucket, filename):
    content = _make_investigation_zip()
    return Response(
        content,
        mimetype='application/zip',
        headers={
            'Content-Disposition': f'attachment; filename="{filename}"',
            'Content-Length': str(len(content)),
        },
    )
